[cats-blender-plugin-unofficial]
src.git = "https://github.com/teamneoneko/Cats-Blender-Plugin-Unofficial-.git"
src.branch = "blender-44"
fetch.git = "https://github.com/teamneoneko/Cats-Blender-Plugin-Unofficial-.git"

[wivrn-solarxr]
src.git = "https://github.com/notpeelz/WiVRn.git"
src.branch = "solarxr-patches"
fetch.git = "https://github.com/notpeelz/WiVRn.git"
