# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cats-blender-plugin-unofficial = {
    pname = "cats-blender-plugin-unofficial";
    version = "7f6b7c3bf9ecc32fb888b09ec18748f41c3dd38b";
    src = fetchgit {
      url = "https://github.com/teamneoneko/Cats-Blender-Plugin-Unofficial-.git";
      rev = "7f6b7c3bf9ecc32fb888b09ec18748f41c3dd38b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-MhHd1kDL/m6IBcb+MBULvI5rKPcU4WdwRSmse4OsZCE=";
    };
    date = "2025-06-04";
  };
  disblock-origin = {
    pname = "disblock-origin";
    version = "8a16d321a9f76b9c0bba1257ccd78ccd92070baa";
    src = fetchgit {
      url = "https://git.allpurposem.at/mat/Disblock-Origin.git";
      rev = "8a16d321a9f76b9c0bba1257ccd78ccd92070baa";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-KNUY+OGhftx9Cj5N2ynTa1wlUwQ5MQdSGf2S8tuy0Jk=";
    };
    date = "2025-07-24";
  };
  osc-goes-brrr = {
    pname = "osc-goes-brrr";
    version = "a3f951756bdeefcc690b98d4c4f22c2230464be7";
    src = fetchgit {
      url = "https://github.com/OscToys/OscGoesBrrr.git";
      rev = "a3f951756bdeefcc690b98d4c4f22c2230464be7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-KRx8rMsQFU7dYmjO/JCjkUp2JheTkQ8sUT56Q0Q+p8E=";
    };
    date = "2024-10-13";
  };
}
