# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cats-blender-plugin-unofficial = {
    pname = "cats-blender-plugin-unofficial";
    version = "3bcf8d5f0678c1eb5336dd38540a346aaca39c90";
    src = fetchgit {
      url = "https://github.com/teamneoneko/Cats-Blender-Plugin-Unofficial-.git";
      rev = "3bcf8d5f0678c1eb5336dd38540a346aaca39c90";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Zo8D2P0Bsm1jsp9p/93ZRYO+4+cWljQn8yNotsnIQ/M=";
    };
    date = "2025-05-30";
  };
  osc-goes-brrr = {
    pname = "osc-goes-brrr";
    version = "a3f951756bdeefcc690b98d4c4f22c2230464be7";
    src = fetchgit {
      url = "https://github.com/OscToys/OscGoesBrrr.git";
      rev = "a3f951756bdeefcc690b98d4c4f22c2230464be7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-KRx8rMsQFU7dYmjO/JCjkUp2JheTkQ8sUT56Q0Q+p8E=";
    };
    date = "2024-10-13";
  };
  wivrn-solarxr = {
    pname = "wivrn-solarxr";
    version = "78660045c01b3818b06771480957e60262481767";
    src = fetchgit {
      url = "https://github.com/notpeelz/WiVRn.git";
      rev = "78660045c01b3818b06771480957e60262481767";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-QCU0bu1Rrptr3TUTFg0wypnqNpilxwShhpKRryL1Tug=";
    };
    date = "2025-06-06";
  };
}
