# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cats-blender-plugin-unofficial = {
    pname = "cats-blender-plugin-unofficial";
    version = "45032046e3e77a0a397fe1dc482f68cb5444dc59";
    src = fetchgit {
      url = "https://github.com/teamneoneko/Cats-Blender-Plugin-Unofficial-.git";
      rev = "45032046e3e77a0a397fe1dc482f68cb5444dc59";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-8n5VI2kAdxmuapSmiHtG2yrwy3wvtksbVtQ29cys2j8=";
    };
    date = "2025-03-26";
  };
  wivrn-solarxr = {
    pname = "wivrn-solarxr";
    version = "415bb70fd881e60a6bcaf95aaebc04eff0901e44";
    src = fetchgit {
      url = "https://github.com/notpeelz/WiVRn.git";
      rev = "415bb70fd881e60a6bcaf95aaebc04eff0901e44";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-v38v3cyix5A7HM88ryJmvDOo0ycZqqBZwO+hqgxoSIA=";
    };
    date = "2025-05-22";
  };
}
