# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cats-blender-plugin-unofficial = {
    pname = "cats-blender-plugin-unofficial";
    version = "b1a8cbb525e995d48423a1b55381c0d64e65c54f";
    src = fetchgit {
      url = "https://github.com/teamneoneko/Cats-Blender-Plugin-Unofficial-.git";
      rev = "b1a8cbb525e995d48423a1b55381c0d64e65c54f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Yuq9g+PjrT8H7nEYLs7TfX/zUbEf8Txgblc/xjNMNuE=";
    };
    date = "2025-11-20";
  };
  disblock-origin = {
    pname = "disblock-origin";
    version = "230a9a9c25d4d51be2200e8aecec7274967a1090";
    src = fetchgit {
      url = "https://git.allpurposem.at/mat/Disblock-Origin.git";
      rev = "230a9a9c25d4d51be2200e8aecec7274967a1090";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-6yPmcKNNWaejRGHDgtkhOcsiDSldcH80HSdmTym2Jqw=";
    };
    date = "2025-12-16";
  };
  osc-goes-brrr = {
    pname = "osc-goes-brrr";
    version = "6a3421f0a755e990238b2d75b71b66430f029929";
    src = fetchgit {
      url = "https://github.com/OscToys/OscGoesBrrr.git";
      rev = "6a3421f0a755e990238b2d75b71b66430f029929";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-JC86IHzntcgqdAcGAUotX7iwj3iIQwC2j2O3+QA77Tw=";
    };
    date = "2025-11-17";
  };
  winetricks = {
    pname = "winetricks";
    version = "533f41704766765cfb3706fb2aa197acbb05df32";
    src = fetchgit {
      url = "https://github.com/Winetricks/winetricks.git";
      rev = "533f41704766765cfb3706fb2aa197acbb05df32";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Bt5wo7zEAN9Mh9dwbGPsSW8pt1ruBrn0Br9BdprtIRY=";
    };
    date = "2025-11-04";
  };
}
