# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cats-blender-plugin-unofficial = {
    pname = "cats-blender-plugin-unofficial";
    version = "57de0a2c88b4208579978b160383011e565a153c";
    src = fetchgit {
      url = "https://git.disroot.org/Neoneko/Cats-Blender-Plugin.git";
      rev = "57de0a2c88b4208579978b160383011e565a153c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-dW1t2lhRRAwzLTvn+6bG48XwdKWfdVfjWw9QHJNGLU8=";
    };
    date = "2025-12-17";
  };
  disblock-origin = {
    pname = "disblock-origin";
    version = "15cbab89197af9f4af6b404ad0c5ea922cc9c380";
    src = fetchgit {
      url = "https://git.allpurposem.at/mat/Disblock-Origin.git";
      rev = "15cbab89197af9f4af6b404ad0c5ea922cc9c380";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-mIDj3gf4I1f+u/jzqeNiIqLaR173bkxO9Nq0PBXhws8=";
    };
    date = "2026-01-14";
  };
  osc-goes-brrr = {
    pname = "osc-goes-brrr";
    version = "6a3421f0a755e990238b2d75b71b66430f029929";
    src = fetchgit {
      url = "https://github.com/OscToys/OscGoesBrrr.git";
      rev = "6a3421f0a755e990238b2d75b71b66430f029929";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-JC86IHzntcgqdAcGAUotX7iwj3iIQwC2j2O3+QA77Tw=";
    };
    date = "2025-11-17";
  };
  winetricks = {
    pname = "winetricks";
    version = "81a692e2ee6b311367f18a17a9a61a0ef1c0ad18";
    src = fetchgit {
      url = "https://github.com/Winetricks/winetricks.git";
      rev = "81a692e2ee6b311367f18a17a9a61a0ef1c0ad18";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-5yUKmLrj/nUFzgRv/afAcOjO3pwQWFWWD9pvKY2upbI=";
    };
    date = "2025-12-23";
  };
}
