# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cats-blender-plugin-unofficial = {
    pname = "cats-blender-plugin-unofficial";
    version = "9266abbd4fb51ce953ddf40a4eaa057b18cc18c4";
    src = fetchgit {
      url = "https://github.com/teamneoneko/Cats-Blender-Plugin-Unofficial-.git";
      rev = "9266abbd4fb51ce953ddf40a4eaa057b18cc18c4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-su4YHNyc6jmAftaYHE9UpuvuDk5YxZqhGoIEFrMobsM=";
    };
    date = "2025-07-29";
  };
  disblock-origin = {
    pname = "disblock-origin";
    version = "6709893e5c35a1770868cc5bf193e088bdd903c7";
    src = fetchgit {
      url = "https://git.allpurposem.at/mat/Disblock-Origin.git";
      rev = "6709893e5c35a1770868cc5bf193e088bdd903c7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-p9aJUA3eGf1pHFVLgBRzQVPVk9aL4a/v/VUYBeWe0SA=";
    };
    date = "2025-08-04";
  };
  osc-goes-brrr = {
    pname = "osc-goes-brrr";
    version = "a3f951756bdeefcc690b98d4c4f22c2230464be7";
    src = fetchgit {
      url = "https://github.com/OscToys/OscGoesBrrr.git";
      rev = "a3f951756bdeefcc690b98d4c4f22c2230464be7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-KRx8rMsQFU7dYmjO/JCjkUp2JheTkQ8sUT56Q0Q+p8E=";
    };
    date = "2024-10-13";
  };
}
